### ISSUE TITLE
Where can I download tiny_imagenet and lsun?

### ISSUE THREAD

**Issue by ironartisan** [mmasana/OoD_Mining#3]
Traceback (most recent call last):
  File "C:/Users/ChenYL/Desktop/temp/github/OoD_Mining/src/ODM_svhn_cifar10.py", line 173, in <module>
    tiny_x = utdata.load_test(tiny_path, 32)
  File "C:\Users\ChenYL\Desktop\temp\github\OoD_Mining\src\utils\utils_datasets.py", line 46, in load_test
    fid = open(path + "images.txt", "r")
FileNotFoundError: [Errno 2] No such file or directory: 'data/tiny_imagenet/images.txt'
@mmasana  Where did images.txt come from?thank you

**Comment by mmasana** [comment]
Tiny Imagenet and LSUN can be downloaded from their respective webpages [[tiny](https://tiny-imagenet.herokuapp.com/)] [[lsun](https://www.yf.io/p/lsun)]. However, I also recommend checking [this download version](https://github.com/facebookresearch/odin#downloading--out-of-distribtion-datasets) from the authors of the ODIN paper, which we also compare to.

Since those datasets are used only as out-of-distribution, no labels are needed for the specific classes. Therefore, the loading function only needs `images.txt` to be a file with each image name (full path) per line, as commented in the code [here](https://github.com/mmasana/OoD_Mining/blob/77c81b5603c2b55532187b2cd2126dd8b617e6e3/src/utils/utils_datasets.py#L41).

Hope this solves the issue.
